
package blue.cat.pixel.testwebservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.6
 * Sat Sep 07 19:23:28 WEST 2013
 * Generated source version: 2.7.6
 */

@XmlRootElement(name = "whatIsTheAnswerResponse", namespace = "http://testwebservice.pixel.cat.blue/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "whatIsTheAnswerResponse", namespace = "http://testwebservice.pixel.cat.blue/")

public class WhatIsTheAnswerResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

