
package blue.cat.pixel.testwebservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.6
 * Sat Sep 07 19:23:28 WEST 2013
 * Generated source version: 2.7.6
 */

@XmlRootElement(name = "whatIsTheAnswer", namespace = "http://testwebservice.pixel.cat.blue/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "whatIsTheAnswer", namespace = "http://testwebservice.pixel.cat.blue/")

public class WhatIsTheAnswer {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

